# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M8jaZCEHaLmYmBq5udQs80RMKaRU1YtB
"""

!pip install streamlit

import streamlit as st

def main():
  st.write("Testing Website")

if __name__ == "__main__":
    main()